### PR TITLE
Temporal: workflow plumbing

### LINKED ISSUE #3940: [Upsert Queue] Temporal worker
As per design doc [design doc](https://www.notion.so/dust-tt/Design-Doc-Upsert-Queue-4430f703e2db42f1a3cf2ea962d6e020).

Write the Temporal worker code, along with the Activity Interceptor for monitoring activities that have failed more than 20 times.

### PR DESCRIPTION
**Pull request by spolu**
## Description

Fixes: https://github.com/dust-tt/dust/issues/3940

- Define the plumbing and client of the temporal workflow for the upsert queue.

## Risk

This will create a new worker but it won't do much for now.

## Deploy Plan

- deploy `front`

### CODE REVIEW

File: front/upsert_queue/temporal/client.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+  dataSourceName: string,
+  upsertQueueId: string
+): Promise<Result<string, Error>> {
+  const client = await getTemporalClient();
+
+  const workflowId = `upsert-queue-document-${workspaceId}-${dataSourceName}-${upsertQueueId}`;
+
+  try {
+    await client.workflow.start(upsertDocumentWorkflow, {
+      args: [upsertQueueId],
```
Comment (lasryaric) [inline front/upsert_queue/temporal/client.ts:21]: Add search tags.
WorkspaceId and dataSourceName?

**Review by lasryaric — APPROVED** [review]
LGTM.
