### PR TITLE
[extension] handle missing events

### LINKED ISSUE #8808: [Ext] Correctly handle new stream events in extension
Adding a new event type in the streams (message or conversation) is common, but this actually an important api change, as we'll get new types that were not in the contract before. Usually we force the handling of new event in the code with `switch/case/default/assertNever` pattern - however in the extension, as a specific version is deployed and won't be immediately updated, we'll run into the default and will get "This should never happen" errors. 
It's better to silently ignore these events instead of crashing the extension.

### PR DESCRIPTION
**Pull request by tdraier**
fixes: https://github.com/dust-tt/dust/issues/8808 

## Description

Add new events, ignore future missing

### CODE REVIEW

File: extension/app/src/lib/asserNever.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+export function assertNeverAndIgnore(x: never): void {
+  console.log(
```
Comment (PopDaph) [inline extension/app/src/lib/asserNever.ts:2]: We can maybe console.error?

Also maybe we can add some more comment to explain why we have to do this? Cause it's clear for us both why but maybe not everyone is aware of the contraints of the release for the Chrome extension?

**Review by PopDaph — APPROVED** [review]
Thanks a lot for catching this sooner than later. This could have become a real pain for us 🙏🏻
