### PR TITLE
[front] fix(vaults): Fix vault creation

### LINKED ISSUE #6786: [Groups UI] Fix create vault

### PR DESCRIPTION
**Pull request by tdraier**
fixes:  https://github.com/dust-tt/dust/issues/6786 https://github.com/dust-tt/dust/issues/6787

## Description

- Always display the vaults section
- Reload list of vaults after creation
- Redirect to new vault after creation
- Hide files from system
- Scroll on members list

## Risk

-
## Deploy Plan

deploy `front`

### CODE REVIEW

File: front/components/vaults/CreateVaultModal.tsx [hunk 1]
```diff
@@ -128,7 +130,12 @@ export function CreateVaultModal({
         const errorData = await res.json();
         throw new Error(errorData.error?.message || "Failed to create vault");
       }
-      return await res.json();
+      const r: PostVaultsResponseBody = await res.json();
+
+      // Invalidate the vaults list
+      await mutate(`/api/w/${owner.sId}/vaults`);
```
Comment (flvndvd) [inline front/components/vaults/CreateVaultModal.tsx:136]: We avoid using the global mutate and we prefer using the local one I guess the one from `useVaults` in this case.

**Review by flvndvd — APPROVED** [review]
LGTM, one comment is fixed.
