### PR TITLE
Fix the Zendesk ticket `sourceUrl` upserted to `core`

### LINKED ISSUE #10398: Investigate burst of Zendesk-related diffs
- See [here](https://app.datadoghq.eu/logs?query=CoreNodes%20-%22Latency%20between%20connectors%20and%20core%22%20%40provider%3Azendesk&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=false&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1738230456724&to_ts=1738234056724&live=true).

### PR DESCRIPTION
**Pull request by aubin-tchoi**
## Description

- Closes https://github.com/dust-tt/dust/issues/10398.
- The value in connectors was always correct whereas the `documentUrl` upserted to core was incorrect.

## Risk

- Low.

## Deploy Plan

- Deploy connectors.
- Full resync the connectors where we had the issue.

### CODE REVIEW

File: connectors/src/connectors/zendesk/lib/sync_ticket.ts [hunk 1]
```diff
@@ -224,7 +225,7 @@ ${comments
       dataSourceConfig,
       documentId,
       documentContent,
-      documentUrl: ticket.url,
+      documentUrl: ticketUrl,
```
Comment (aubin-tchoi) [inline connectors/src/connectors/zendesk/lib/sync_ticket.ts:228]: this line was the issue, we used `ticket.url` instead of the reformatted url

**Review by PopDaph — APPROVED** [review]
