### PR TITLE
[front] - fix(apps): adjust tabs visibility on role 

### LINKED ISSUE #7530: [Polish] As a user in a Dust App since I'm read-only  I want to see only the Spec & Dataset tabs

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

This PR aims at hiding the "logs" and "settings" tabs of Dust Apps for "users".

**References:**
- https://github.com/dust-tt/dust/issues/7530

## Risk

Low

## Deploy Plan

Deploy `front`

### CODE REVIEW

File: front/poke/swr/data_source_views.ts [hunk 1]
```diff
@@ -3,6 +3,7 @@ import type {
   DataSourceViewType,
   LightWorkspaceType,
 } from "@dust-tt/types";
+import type { PaginationState } from "@tanstack/react-table";
```
Comment (JulesBelveze) [inline front/poke/swr/data_source_views.ts:6]: 🤷🏼‍♂️ my linter

**Review by PopDaph — APPROVED** [review]
🙏🏻
