### PR TITLE
[front] Fixes in website edition/creation

### LINKED ISSUE #7613: Errors in form quickly appear when closing add/edit website modal

### PR DESCRIPTION
**Pull request by tdraier**
fixes: https://github.com/dust-tt/dust/issues/7613
fixes: https://github.com/dust-tt/tasks/issues/1371
## Description

- add loading state when configuration is not loaded
- call mutate after modification
- close modal after delete
- cleanup state on open, not on close, to keep content when modal close

Screenshot 2024-09-23 at 17 15 18

## Deploy Plan

deploy front

### CODE REVIEW

File: front/components/vaults/VaultWebsiteModal.tsx [hunk 1]
```diff
@@ -134,6 +100,49 @@ export default function VaultWebsiteModal({
     );
   const [advancedSettingsOpened, setAdvancedSettingsOpened] = useState(false);
   const [headers, setHeaders] = useState<{ key: string; value: string }[]>([]);
+  console.log("--", dataSourceName);
```
Comment (JulesBelveze) [inline front/components/vaults/VaultWebsiteModal.tsx:103]: ✂️

File: front/components/vaults/VaultWebsiteModal.tsx [hunk 2]
```diff
@@ -373,142 +388,185 @@ export default function VaultWebsiteModal({
...
-                    <Button
-                      variant="tertiary"
-                      labelVisible={false}
-                      label=""
-                      icon={XMarkIcon}
-                      disabledTooltip={true}
-                      onClick={() => {
-                        const newHeaders = headers.filter(
-                          (_, i) => i !== index
+                    <div>
```
Comment (JulesBelveze) [inline front/components/vaults/VaultWebsiteModal.tsx:520]: Can we get rid of this div?

**Review by JulesBelveze — APPROVED** [review]
LGTM
