### PR TITLE
Mutli-actions: various fixes

### LINKED ISSUE #5589: [Multi-Actions] Investigate stuck actions
https://front-edge.dust.tt/w/0ec9852c2f/assistant/653fdfdb74
https://dust.tt/w/0ec9852c2f/assistant/d6d34ec265

### PR DESCRIPTION
**Pull request by spolu**
## Description

Fixes: https://github.com/dust-tt/dust/issues/5589

- Fix chip thinking status when message is cancelled
- Fix issue when the model decides to run a tool even if no tool were provided when we've reached maxToolUsePerRun, the action would be run and we would escape the loop and drop the agent message flat (which would remain in `created` status). Instead we error explicitly if that happens.\
- Simplify the logic of generation/actions presence + fix a bug that could happen if the generation is empty but set (not sure it can really realize but from a type standpoint it can)

## Risk

N/A

## Deploy Plan

- deploy `front`

### CODE REVIEW

File: front/components/assistant/conversation/actions/AgentMessageActions.tsx [hunk 1]
```diff
@@ -24,32 +22,41 @@ export function AgentMessageActions({
   // This workaround will be replaced by proper streaming events in the future.
```
Comment (flvndvd) [inline front/components/assistant/conversation/actions/AgentMessageActions.tsx:22]: Let's update the comment to reflect the update, right?

File: front/lib/api/assistant/agent.ts [hunk 2]
```diff
@@ -668,18 +654,47 @@ export async function* runMultiActionsAgent(
...
       configurationId: agentConfiguration.sId,
       messageId: agentMessage.sId,
       error: {
-        code: "no_action_or_generation_found",
-        message: "No action or generation found",
+        code: "multi_actions_error",
+        message:
+          "Assistant failed to generate response after running `maxToolsUsePerRun`.",
       },
     } satisfies AgentErrorEvent;
```
Comment (flvndvd) [inline front/lib/api/assistant/agent.ts:697]: Return?

**Review by flvndvd — APPROVED** [review]
