### PR TITLE
Fix snowflake missing and extra nodes

### LINKED ISSUE #10400: Fix exclusion rule for Snowflake != root call
- The root call in Snowflake is expected to have a slightly different behavior between core and connectors.
- https://github.com/dust-tt/dust/pull/10357/files aims at ignoring this diff, but is slightly incorrects and still shows up in the [log](https://app.datadoghq.eu/logs?query=CoreNodes%20-%22Latency%20between%20connectors%20and%20core%22%20%40provider%3Asnowflake&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZS39W_R6cGTpgAAABhBWlMzOVhrTkFBQ2pzbERWdk9fZDNnQk8AAAAkMDE5NGI3ZmItZGMyNC00MzVlLWFkN2ItYTRiMjUzNGNhMjRjAAZ8XQ&fromUser=false&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1738230456724&to_ts=1738234056724&live=true).
- The log is most likely due to this, if not it should be investigated.

### PR DESCRIPTION
**Pull request by overmode**
## Description
- parentsIn leads to a nodes query with internalIds set -> not a root call
- modified log in computeNodesDiff to also log parentsIn
- Fixes #10400  

## Tests
- Fetch a few nodes locally

## Risk
Low

## Deploy Plan
Deploy front

### CODE REVIEW

**Review by philipperolet — APPROVED** [review]
:+1:

**Review by philipperolet — APPROVED** [review]

File: front/lib/api/content_nodes.ts [hunk 1]
```diff
@@ -91,7 +94,22 @@ export function computeNodesDiff({
         connectorsNode.internalId !== "notion-unknown" &&
         !connectorsNode.internalId.startsWith("slack-channel-")
       ) {
-        missingNodes.push(connectorsNode);
+        if (
+          // For snowflake we ignore the missing nodes if we returned a node that is a parent.
+          // This is because connectors returns all children tables when fed with internalIds while core returns only these ids
+          // See https://github.com/orgs/dust-tt/projects/3/views/1?pane=issue&itemId=95859834&issue=dust-tt%7Cdust%7C10400
```
Comment (spolu) [inline front/lib/api/content_nodes.ts:100]: small nit: the project view pane might gets removed, ideally we link the issue directly :+1:

File: front/lib/api/data_source_view.ts [hunk 2]
```diff
@@ -462,9 +462,11 @@ export async function getContentNodesForDataSourceView(
     dataSourceViewId: dataSourceView.sId,
     provider: dataSourceView.dataSource.connectorProvider,
     viewType: params.viewType,
-    isRootCall: !params.parentId && !params.internalIds,
+    isRootCall:
+      !params.parentId && !params.internalIds && !dataSourceView.parentsIn,
     parentId: params.parentId,
     internalIds: params.internalIds,
+    parentsIn: dataSourceView.parentsIn || undefined,
```
Comment (aubin-tchoi) [inline front/lib/api/data_source_view.ts:469]: nit: not sure what the || undefined does here

File: front/lib/api/content_nodes.ts [hunk 3]
```diff
@@ -350,6 +368,19 @@ export function computeNodesDiff({
       (coreNode) =>
         provider !== "slack" ||
         !coreNode.internalId.startsWith("slack-channel-")
+    )
+    // Snowflake schemas are returned from core, while connector only return tables
+    // Detect schema for which we have a table in connectors and ignore them.
+    // See https://github.com/orgs/dust-tt/projects/3/views/1?pane=issue&itemId=95859834&issue=dust-tt%7Cdust%7C10400
```
Comment (aubin-tchoi) [inline front/lib/api/content_nodes.ts:374]: link the issue instead?

File: front/lib/api/content_nodes.ts [hunk 4]
```diff
@@ -350,6 +368,19 @@ export function computeNodesDiff({
...
+    .filter(
+      (coreNode) =>
+        !(
+          provider === "snowflake" &&
+          coreNode.internalId.split(".").length === 2 &&
```
Comment (aubin-tchoi) [inline front/lib/api/content_nodes.ts:379]: that would be a <= 2 to handle dbs too no?

File: front/lib/api/content_nodes.ts [hunk 5]
```diff
@@ -91,7 +94,22 @@ export function computeNodesDiff({
...
         !connectorsNode.internalId.startsWith("slack-channel-")
       ) {
-        missingNodes.push(connectorsNode);
+        if (
+          // For snowflake we ignore the missing nodes if we returned a node that is a parent.
+          // This is because connectors returns all children tables when fed with internalIds while core returns only these ids
+          // See https://github.com/orgs/dust-tt/projects/3/views/1?pane=issue&itemId=95859834&issue=dust-tt%7Cdust%7C10400
+          !(
+            provider === "snowflake" &&
+            coreNodes.some((n) =>
```
Comment (aubin-tchoi) [inline front/lib/api/content_nodes.ts:103]: `very nit`: in the inverse check below you add a safeguard on `internalId.split(".").length` that handily handles cases where a table name is a prefix of another table's, seems odd to do it at one place but not the other

Comment (aubin-tchoi) [inline front/lib/api/content_nodes.ts:103]: that would be `coreContentNodes` (I should have renamed `coreNodes` into smth like `matchesInCore`)

File: front/lib/api/content_nodes.ts (hunk 1 above)
Comment (overmode) [reply front/lib/api/content_nodes.ts:100]: Adressed in https://github.com/dust-tt/dust/pull/10465
