### PR TITLE
[front fix: Reload dataSource view detail after modification

### LINKED ISSUE #7633: [Bug] Company Data - Folders: Edits to Folder Descriptions Are Not Visible Without Page Refresh
**Description**
When a user edits a folder description and saves the changes, the updated description is not displayed in the UI immediately. The previous folder description continues to be shown until the page is refreshed.

**Videos/Screenshots**
[Loom](https://www.loom.com/share/754a2a92610a43549bdefc0790e92aa3?sid=c6be308b-6100-4eff-9f32-c3ef16054d98)

**Steps to Reproduce**
1. Navigate to "Data sources".
2. Select "Folders".
3. Edit an existing folder by updating the folder description.
4. After saving changes, re-open the edit folder drawer and observe that the updated description is not displayed.
5. Refresh the page, re-open the edit folder drawer, and observe that the updated description is displayed.

### PR DESCRIPTION
**Pull request by tdraier**
fixes: https://github.com/dust-tt/dust/issues/7633

## Description

- Use a view id as prop in VaultFolderModal and load the folder view through swr. 
- invalidate query after update
- cleanup modal reset
- Simplify VaultWebsiteModal to have teh same behaviour - move hooks calls inside the modal where it's used.

## Risk

-

## Deploy Plan

deploy front

### CODE REVIEW

File: front/lib/swr/vaults.ts [hunk 1]
```diff
@@ -280,8 +302,6 @@ export function useUpdateFolder({
       }
     );
     if (res.ok) {
-      void mutateVaultDataSourceViews();
```
Comment (JulesBelveze) [inline front/lib/swr/vaults.ts:283]: Any reason we're getting rid of the mutate here?

**Review by JulesBelveze — APPROVED** [review]
Looks good 👌🏼

File: front/lib/swr/vaults.ts (hunk 1 above)
Comment (tdraier) [reply front/lib/swr/vaults.ts:283]: yes, it's useless - we're updating the description, and description is not used in the views list ( I rather call mutate of the single view query in VaultFolderModal to correctly relaod description after update)
