### PR TITLE
[front] - fix(ds/managed): empty managed `DataSourceView`

### LINKED ISSUE #7212: [Vaults] - Empty managed DataSourceView

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

This PR aims at fixing the managed data source view screen when no data was added to it. The "Add data" button redirects to the managed data source view screen (as adding/removing data will now be done through a side modal when clicking on "manage").

See screenshots below:

Previously:
Screenshot 2024-09-05 at 14 17 31

Now:
Screenshot 2024-09-05 at 14 08 26

## Risk

None

## Deploy Plan

Deploy `front`

### CODE REVIEW

File: front/components/vaults/VaultDataSourceViewContentList.tsx [hunk 1]
```diff
@@ -157,6 +158,22 @@ export const VaultDataSourceViewContentList = ({
...
+        ) : dataSourceView.category === "managed" ? (
+          <div className="flex flex-col items-center gap-2 text-sm text-element-700">
+            <span>No data sources were added yet.</span>
+            <Button
+              variant="primary"
+              icon={PlusIcon}
+              label="Add data"
+              onClick={() => {
+                void router.push(
+                  `/w/${owner.sId}/data-sources/vaults/${vault.sId}/categories/${dataSourceView.category}`
```
Comment (PopDaph) [inline front/components/vaults/VaultDataSourceViewContentList.tsx:170]: So you redirect to the parent page? 
Shouldn't we allow configuring the connection when we're on the root page of the connection instead?

Comment (PopDaph) [reply front/components/vaults/VaultDataSourceViewContentList.tsx:170]: Yes if we're at the root of the Connection. You can check with @Duncid before implementing but this would seem legit (and better UX than putting you back on the list of Connections where you have to understand you have to click on "Manage").

Comment (JulesBelveze) [reply front/components/vaults/VaultDataSourceViewContentList.tsx:170]: Seems indeed better, like it 😇

**Comment by PopDaph** [comment]
(Discussed IRL yesterday: we'll move the modals in a component with the button to open them so that all code is isolated in a file and easier to use in multiple places)

File: front/components/ConnectorPermissionsModal.tsx [hunk 2]
```diff
@@ -28,71 +46,320 @@ const PERMISSIONS_EDITABLE_CONNECTOR_TYPES: Set<ConnectorProvider> = new Set([
...
+  owner: LightWorkspaceType;
+  user: UserType;
+}
+
+export async function handleUpdatePermissions(
+  connector: ConnectorType,
+  dataSource: DataSourceType,
+  owner: LightWorkspaceType,
+  dustClientFacingUrl: string,
+  sendNotification: (notification: NotificationType) => void
```
[the remark this answers is not in the document]
Comment (JulesBelveze) [reply front/components/ConnectorPermissionsModal.tsx:70]: IIRC you can't call a hook in a function that's not a hook nor a `React.FC` 😇

File: front/components/ConnectorPermissionsModal.tsx [hunk 3]
```diff
@@ -28,71 +46,320 @@ const PERMISSIONS_EDITABLE_CONNECTOR_TYPES: Set<ConnectorProvider> = new Set([
...
   isAdmin: boolean;
+  user: UserType;
+  onManageButtonClick?: () => void;
 }) {
   const { mutate } = useSWRConfig();
 
   const [updatedPermissionByInternalId, setUpdatedPermissionByInternalId] =
     useState<Record<string, ConnectorPermission>>({});
+  const [showEditionModal, setShowEditionModal] = useState(false);
+  const [showDataSelectionModal, setShowDataSelectionModal] = useState(false);
```
Comment (Fraggle) [inline front/components/ConnectorPermissionsModal.tsx:362]: can only one of theses be true at the same time ?
if so, what about a `const modalToShow:string = "" | "edition" | "selection";` to enforce the behavior ?

**Review by Fraggle — APPROVED** [review]
LGTM, general feedbacks:
- If you are interested in the logged-in user, just use `useUser()` directly to avoid useless props.
- Same for `isAdmin` can be done as `owner.role === 'admin'`
- I would replace the anonymous callbacks as props by extracted functions wrapped in `useCallback(...)` at the beggining of the component (to avoid re-rendering and improve lisibility).

File: front/components/ConnectorPermissionsModal.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (Fraggle) [reply front/components/ConnectorPermissionsModal.tsx:70]: Ah sorry, I didn't notice it wasn't a component.

**Comment by Duncid** [comment]
@JulesBelveze 

Here is the copy!

"Connection ready. Select the data to sync."
