### PR TITLE
[front] - fix(DataTable): improve DataTable responsiveness

### LINKED ISSUE #7400: [UX] - Add `columnBreakpoints` to `DataTable`
Current uses of `DataTable` components do not specify any `columnsBreakpoints` which makes the components not responsive.

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

This PR aims at enhancing the responsiveness of the `DataTable` components used throughout the app by passing a `columnsBreakpoints` parameter.

**References:**
- https://github.com/dust-tt/dust/issues/7400

## Risk

Low, only touches front components

## Deploy Plan

Deploy `front`

### CODE REVIEW

File: front/components/vaults/CreateOrEditVaultModal.tsx [hunk 1]
```diff
@@ -102,9 +102,21 @@ export function CreateOrEditVaultModal({
         id: "name",
         accessorKey: "name",
         cell: (info: Info) => (
-          <DataTable.CellContent avatarUrl={info.row.original.icon}>
-            {info.row.original.name}
-          </DataTable.CellContent>
+          <>
```
Comment (JulesBelveze) [inline front/components/vaults/CreateOrEditVaultModal.tsx:105]: Note: did this manually as it would be weird not to show the email while allowing to search on the email..

File: front/components/vaults/VaultResourcesList.tsx [hunk 2]
```diff
@@ -103,7 +103,7 @@ const getTableColumns = ({
     meta: {
       width: "6rem",
     },
-    id: "managedBy",
+    accessorKey: "managedBy",
```
Comment (tdraier) [inline front/components/vaults/VaultResourcesList.tsx:106]: don't you need to have an id to make columnsBreakpoints work ?

Comment (JulesBelveze) [reply front/components/vaults/VaultResourcesList.tsx:106]: That's what I also thought, but seems like `accessorKey` does the job and "id" as well 🤷🏼‍♂️

Comment (JulesBelveze) [reply front/components/vaults/VaultResourcesList.tsx:106]: Don't mind setting "id" everywhere instead of "accessorKey" if you prefer

Comment (tdraier) [reply front/components/vaults/VaultResourcesList.tsx:106]: let's keep accessorKey only if it's the same value ..

**Review by tdraier — APPROVED** [review]
