### PR TITLE
[extension] Handle login errors

### LINKED ISSUE #8746: [Ext] Better feedback for login errors
If user is not found, we should show a page telling the user has to create an account through the app first. Currently, login fails with no feedback.

### PR DESCRIPTION
**Pull request by tdraier**
fixes: https://github.com/dust-tt/dust/issues/8746

## Description

- Send specific error if the user is not regsitered
- Store error and shows it in login page
- Add link to sign up if user does not exist
- Force login prompt in case of error.

### CODE REVIEW

File: extension/app/src/components/auth/useAuth.ts [hunk 1]
```diff
@@ -63,11 +69,11 @@ export const useAuthHook = () => {
...
-      if (changes.accessToken && !changes.accessToken.newValue) {
-        console.log("Access token removed from storage.");
-        setTokens(null);
-        setUser(null);
-      }
+      // if (changes.accessToken && !changes.accessToken.newValue) {
+      //   console.log("Access token removed from storage.");
+      //   setTokens(null);
+      //   setUser(null);
+      // }
```
Comment (tdraier) [inline extension/app/src/components/auth/useAuth.ts:76]: I had to comment this - otherwise we're unlogged when the token change (so on rfresh)

Comment (PopDaph) [reply extension/app/src/components/auth/useAuth.ts:76]: Very weird because this checks that we do not receive a new value of the token (no `newValue`)

File: extension/app/src/lib/auth.ts [hunk 2]
```diff
@@ -14,29 +17,47 @@ import {
...
+}
+
 // Login sends a message to the background script to call the auth0 login endpoint.
 // It saves the tokens in the extension and schedules a token refresh.
 // Then it calls the /me route to get the user info.
-export const login = async (): Promise<
-  { tokens: StoredTokens; user: StoredUser } | undefined
-> => {
+export const login = async (
+  forceLogin?: boolean
```
Comment (PopDaph) [inline extension/app/src/lib/auth.ts:44]: NIT NIT: could we "booleanize" the name `isForceLogin`?

File: extension/app/src/lib/auth.ts [hunk 3]
```diff
@@ -60,35 +81,48 @@ export const logout = async (): Promise<boolean> => {
...
-      `Failed to fetch /me: ${response.status} ${response.statusText}`
-    );
+    return new Err(new AuthError(me.error.type, me.error.message));
   }
-  const me = await response.json();
-  return me;
+  return new Ok(me);
+};
+
+export const useAuthErrorCheck = (error: any) => {
```
Comment (PopDaph) [inline extension/app/src/lib/auth.ts:120]: Why do we have it twice? (here and in extension/app/src/hooks/useAuthErrorCheck.ts)

File: extension/app/src/components/conversation/usePublicConversation.ts [hunk 4]
```diff
@@ -1,8 +1,8 @@
 import type { ConversationPublicType } from "@dust-tt/client";
-import { logout } from "@extension/lib/auth";
+import { useAuthErrorCheck } from "@extension/hooks/useAuthErrorCheck";
+import {} from "@extension/lib/auth";
```
Comment (PopDaph) [inline extension/app/src/components/conversation/usePublicConversation.ts:3]: NIT: remove?

File: extension/app/src/lib/auth.ts (hunk 3 above)
Comment (tdraier) [reply extension/app/src/lib/auth.ts]: removed

**Comment by tdraier** [comment]
- removed the logout if a refresh token failed, as we may in some cases get multiple refreshes at the same time
- errorCheck is done in useSWR, no need to do it anymore in every hook
- move getAccessCheck to avoid circular deps

File: front/lib/api/auth_wrappers.ts [hunk 5]
```diff
@@ -212,11 +213,22 @@ export function withPublicAPIAuthentication<T, U extends boolean>(
           getRequiredScope(req, opts.requiredScopes)
         );
         if (decoded.isErr()) {
+          const error = decoded.error;
+          if ((error as TokenExpiredError).expiredAt) {
```
Comment (PopDaph) [inline front/lib/api/auth_wrappers.ts:217]: Why do we need the as? 
Could we do `if.error?.expiredAt` ?

**Review by PopDaph — APPROVED** [review]
Thanks a lot 🙏🏻

File: front/lib/api/auth_wrappers.ts (hunk 5 above)
Comment (tdraier) [reply front/lib/api/auth_wrappers.ts:217]: error is of type Error, so `if (error?.expiredAt)` does a `Property 'expiredAt' does not exist on type 'Error'`
