### PR TITLE
[front] fix: fix body height

### LINKED ISSUE #5878: UI: Too large conversation panel in `BuilderLayout`
In the `BuilderLayout` component, when a conversation gets long enough the components become too large to fit into the viewport and get cropped (see picture below)

Image

### PR DESCRIPTION
**Pull request by tdraier**
fixes [#5878](https://github.com/dust-tt/dust/issues/5878)

## Description

Remove the height of the sticky header/topbar (h-16 = 4rem + mb-4 = 1rem) for the body

## Risk

layout only

## Deploy Plan

deploy `front`

### CODE REVIEW

File: front/components/sparkle/AppLayout.tsx [hunk 1]
```diff
@@ -188,7 +188,7 @@ export default function AppLayout({
 
             <div
               className={classNames(
-                "flex h-full w-full flex-col",
```
Comment (JulesBelveze) [inline front/components/sparkle/AppLayout.tsx:191]: Do we have any clue why `height:100%` actually takes more than the full viewport? 🤔

**Review by JulesBelveze — APPROVED** [review]

File: front/components/sparkle/AppLayout.tsx (hunk 1 above)
Comment (JulesBelveze) [inline front/components/sparkle/AppLayout.tsx:191]: Isn't `height:100%` supposed to be 100% of the viewport? 🤔

Comment (tdraier) [reply front/components/sparkle/AppLayout.tsx:191]: h-full is 100% , it's 100% of the parent div - which only works if the parent has a fixed size. 100% of the viewport is 100vh.

Comment (tdraier) [reply front/components/sparkle/AppLayout.tsx:191]: in both cases it's 80 pixel too much :-)

Comment (JulesBelveze) [reply front/components/sparkle/AppLayout.tsx:191]: Yeah yeah sure. Then I guess to properly we would have to modify the layout to have the banner on an other z-index, right?
Anyway, that solves it thanks 🙏

Comment (flvndvd) [reply front/components/sparkle/AppLayout.tsx:191]: Wait why do we need this, given that we have access to the parent div and could constraint there?

Comment (JulesBelveze) [reply front/components/sparkle/AppLayout.tsx:191]: It doesn't seem trivial. Looked a bit and the layout seems a bit flaky 🤔
