### PR TITLE
fix(rate-limiter): swap to Redis LUA script for atomic execution

### LINKED ISSUE #15926: Rate limiting race conditions due to check-then-act algo
The current rate limiting algorithm can be abused by spamming certain endpoints.
e.g [hackerOne#3304261](https://hackerone.com/reports/3304261)

### PR DESCRIPTION
**Pull request by zmarouf**
Fixes: #15926

- Redis LUA scripts are atomic.
- Window trimming happens as a first step via ZREMRANGEBYSCORE
- Request count is retrieved via ZCARD
- We queue requests with ZADD with the time in milliseconds as a score
- We keep the UUIDv4 as a value
- We expire the key with TTL by window + 60s to cleanup

Note: Requests are still visible with ZRANGE and ZCARD until a request arrives. This is because trimming happens pre-count synchronously.

### CODE REVIEW

**Comment by zmarouf** [comment]
Tested locally. Will test on front-edge on the morrow

**Comment by zmarouf** [comment]
Tested on front-edge:
29 requests on API key to be on the edge of the limit followed by 29 requests to simulate the DoS.
Only one request went through on the second batch for a total of 30.
image

File: front/lib/utils/rate_limiter.ts [hunk 1]
```diff
@@ -59,34 +59,68 @@ export async function rateLimiter({
...
+    local window_seconds = tonumber(ARGV[1])
+    local limit = tonumber(ARGV[2])
+    local value = ARGV[3]
+
+    -- Use Redis server time to avoid client clock skew
+    local t = redis.call('TIME') -- { seconds, microseconds }
+    local sec = tonumber(t[1])
+    local usec = tonumber(t[2])
+
+    -- Use milliseconds consistently (backward compatible with prior JS Date.now())
```
Comment (aubin-tchoi) [inline front/lib/utils/rate_limiter.ts]: nit: the in-code comment is not gonna make sense in the future, let's instead leave a small comment in the PR for the future reader 👍🏻

File: front/lib/utils/rate_limiter.ts [hunk 2]
```diff
@@ -59,34 +59,68 @@ export async function rateLimiter({
...
+    local now_ms = sec * 1000 + math.floor(usec / 1000)
+    local window_ms = window_seconds * 1000
+    local trim_before = now_ms - window_ms
+
+    -- Trim old entries outside the window
+    redis.call('ZREMRANGEBYSCORE', key, '-inf', trim_before)
```
Comment (aubin-tchoi) [inline front/lib/utils/rate_limiter.ts]: still not 100% convinced about the change in approach (zcount vs zremrange + zcard). If I was writing it for the first, would've probably gone for the remrange but since we had an implementation with the zcount I would rather do it in two PRs: first the change for atomicity and then the optimization change in algorithmic

**Review by aubin-tchoi — APPROVED** [review]
LGTM, let's make sure to test on front-edge 🙏🏻

File: front/lib/utils/rate_limiter.ts (hunk 2 above)
Comment (zmarouf) [reply front/lib/utils/rate_limiter.ts]: Yep. You're right. I did that last night and forgot to split in two
