### PR TITLE
[connectors] Launch workflows from ZendeskConnectorManager

### LINKED ISSUE #8389: [Zendesk] data source deletion fails at scrub with method not implemetned
Path to reproduce. Create a Zendesk data source. Delete it.

The scrub job will fail with:
```
[16:02:27.943] ERROR (1771900): Unhandled API Error
    method: "DELETE"                    
    url: "/connectors/delete/45?force=true"
    durationMs: 22                              
    headers: {   
      "host": "localhost:3002",
      "connection": "keep-alive",
      "content-type": "application/json",
      "authorization": "[Redacted]",
      "accept": "*/*",         
      "accept-language": "*",    
      "sec-fetch-mode": "cors",          
      "user-agent": "node",         
      "accept-encoding": "gzip, deflate"
    }                        
    error: {                                    
      "type": "Error",     
      "message": "Method not implemented.",
      "stack":     
          Error: Method not implemented.        
              at ZendeskConnectorManager.stop (/home/spolu/code/dust/connectors/src/connectors/zendesk/index.ts:89:11)                  
              at _deleteConnectorAPIHandler (/home/spolu/code/dust/connectors/src/api/delete_connector.ts:32:42)                        
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                             
              at <anonymous> (/home/spolu/code/dust/connectors/src/logger/withlogging.ts:17:7)                                          
    }                               
    error_stack: "Error: Method not implemented.\n    at ZendeskConnectorManager.stop (/home/spolu/code/dust/connectors/src/connectors/zendesk/index.ts:89:11)\n    at _deleteConnectorAPIHandler (/home/spolu/code/dust/connectors/src/api/delete_connector.ts:32:42)\n    at p
rocess.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/home/spolu/code/dust/connectors/src/logger/withlogging.ts:17:7)"  
```

### PR DESCRIPTION
**Pull request by aubin-tchoi**
## Description

- Close [#1523](https://github.com/dust-tt/tasks/issues/1523)
- Close #8389 
- Trigger workflows when creating a connector, setting permissions, resuming.
- Add a pause workflow.
- Implement the pause/unpause and sync.
- Fix the fetching of `ZendeskConfigurations` (`fetchById` mistook for `fetchByConnectorId`).

## Deploy Plan

- Deploy connectors.

### CODE REVIEW

File: connectors/src/connectors/zendesk/index.ts [hunk 1]
```diff
@@ -469,11 +540,33 @@ export class ZendeskConnectorManager extends BaseConnectorManager<null> {
...
-    throw new Error("Method not implemented.");
+    const connectorId = this.connectorId;
+    const connector = await ConnectorResource.fetchById(connectorId);
+    if (!connector) {
+      logger.error({ connectorId }, "[Zendesk] Connector not found.");
+      return new Err(new Error("Connector not found"));
+    }
+    await connector.markAsUnpaused();
+
+    const brandIds = await ZendeskBrandResource.fetchAllBrandIds({
```
Comment (flvndvd) [inline connectors/src/connectors/zendesk/index.ts:564]: Why do we only resume with the `brandIds`?

Comment (aubin-tchoi) [reply connectors/src/connectors/zendesk/index.ts:564]: the brands are the top level collections, syncing them sync everything

File: connectors/src/connectors/zendesk/index.ts [hunk 2]
```diff
@@ -69,6 +72,22 @@ export class ZendeskConnectorManager extends BaseConnectorManager<null> {
       { subdomain: "d3v-dust", conversationsSlidingWindow: 90 }
     );
 
+    const workflowStartResult = await launchZendeskSyncWorkflow({
+      connectorId: connector.id,
+    });
```
[the remark this answers is not in the document]
Comment (aubin-tchoi) [reply connectors/src/connectors/zendesk/index.ts:77]: will do!

File: connectors/src/connectors/zendesk/index.ts [hunk 3]
```diff
@@ -86,15 +105,52 @@ export class ZendeskConnectorManager extends BaseConnectorManager<null> {
...
+      logger.error(
+        {
+          workspaceId: dataSourceConfig.workspaceId,
+          dataSourceId: dataSourceConfig.dataSourceId,
+          error: e,
+        },
+        "[Zendesk] Error resuming the sync workflow."
+      );
+    }
+    return new Ok(undefined);
```
[the remark this answers is not in the document]
Comment (aubin-tchoi) [reply connectors/src/connectors/zendesk/index.ts:133]: true, i'll change that

File: connectors/src/connectors/zendesk/index.ts [hunk 4]
```diff
@@ -86,15 +105,55 @@ export class ZendeskConnectorManager extends BaseConnectorManager<null> {
...
-    throw new Error("Method not implemented.");
+    const { connectorId } = this;
+    const connector = await ConnectorResource.fetchById(connectorId);
+    if (!connector) {
+      logger.error({ connectorId }, "[Zendesk] Connector not found.");
+      return new Err(new Error("Connector not found"));
+    }
+
+    const dataSourceConfig = dataSourceConfigFromConnector(connector);
+    try {
```
Comment (flvndvd) [inline connectors/src/connectors/zendesk/index.ts:120]: Why do we need the try/catch if we have a `Result` type? Also in many other places there is no `try/catch` that wraps this call.

File: connectors/src/connectors/zendesk/index.ts [hunk 5]
```diff
@@ -469,11 +543,33 @@ export class ZendeskConnectorManager extends BaseConnectorManager<null> {
...
+    const { connectorId } = this;
+    const connector = await ConnectorResource.fetchById(connectorId);
+    if (!connector) {
+      logger.error({ connectorId }, "[Zendesk] Connector not found.");
+      return new Err(new Error("Connector not found"));
+    }
+    await connector.markAsPaused();
+    const result = await this.stop();
+
+    return result.isErr() ? result : new Ok(undefined);
```
Comment (flvndvd) [inline connectors/src/connectors/zendesk/index.ts:555]: Same here? Can we simply return result?

File: connectors/src/connectors/zendesk/index.ts [hunk 6]
```diff
@@ -469,11 +543,33 @@ export class ZendeskConnectorManager extends BaseConnectorManager<null> {
...
+      return new Err(new Error("Connector not found"));
+    }
+    await connector.markAsUnpaused();
+
+    const brandIds = await ZendeskBrandResource.fetchAllBrandIds({
+      connectorId,
+    });
+    const result = await launchZendeskSyncWorkflow({ connector, brandIds });
+
+    return result.isErr() ? result : new Ok(undefined);
```
Comment (flvndvd) [inline connectors/src/connectors/zendesk/index.ts:572]: Same here?

File: connectors/src/connectors/zendesk/index.ts (hunk 4 above)
Comment (aubin-tchoi) [reply connectors/src/connectors/zendesk/index.ts:120]: my bad, changed that in `launchZendeskSyncWorkflow` a while ago and got a little bit confused here

Comment (aubin-tchoi) [reply connectors/src/connectors/zendesk/index.ts:120]: goal here is indeed to always use the `Result` type by catching it if necessary in the deepest level possible and return it in `launchZendeskSyncWorkflow` and then in `resume`.

Comment (aubin-tchoi) [reply connectors/src/connectors/zendesk/index.ts:120]: done

File: connectors/src/connectors/zendesk/index.ts (hunk 6 above)
Comment (aubin-tchoi) [reply connectors/src/connectors/zendesk/index.ts:572]: Here types don't match since we pass the workflow ID in the `Ok` of `launchZendeskSyncWorkflow`, turns out we don't need this workflow ID so i'll just change `launchZendeskSyncWorkflow` and return result everywhere appliable

Comment (aubin-tchoi) [reply connectors/src/connectors/zendesk/index.ts]: @flvndvd done

**Review by flvndvd — COMMENTED** [review]
LGTM, left one small comment but good to ship once fixed.

**Review by flvndvd — APPROVED** [review]
