### PR TITLE
[Webcrawler] Fix: saving new webcrawler required 2 clicks on save

### LINKED ISSUE #5592: [Data source] - Need to click on save twice to add new website
When adding a new website one needs to click twice on the "Save" button to actually trigger the save.

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Fixes https://github.com/dust-tt/dust/issues/5592

In the onclick, testing that the form was valid relied on state change, which does not take effect immediately, explaining that the first click was doing nothing

Risk & deploy
---
na

### CODE REVIEW

File: front/components/data_source/WebsiteConfiguration.tsx [hunk 1]
```diff
@@ -266,8 +267,8 @@ export default function WebsiteConfiguration({
           title="Add a Website"
           onSave={() => {
             setIsSubmitted(true);
-            validateForm();
-            if (isValid && !isSaving) {
+            const formValid = validateForm();
```
Comment (PopDaph) [inline front/components/data_source/WebsiteConfiguration.tsx:270]: Now do we still need the `isValid` state? Also, it seems we're calling again validateForm inside handleCreate, could we simplify?

**Review by PopDaph — APPROVED** [review]
Thank you 🙏🏻
