### PR TITLE
[sparkle] - fix: `DataTable` responsiveness

### LINKED ISSUE #6679: [UX] - Responsiveness of `DataTable`
The current implementation of the `DataTable` sparkle component is not responsive. Which causes to slide on horizontally to see the entire table.

While tanstack table does not offer any feature for this, we could simply pass as component's parameters the columns to keep / hide on mobile.

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

This PR aims at modifying the `DataTable` sparkle component to accept a list of columns to hide on mobile.

**References:**
- #6679 

## Risk

None

## Deploy Plan

- Deploy new `sparkle` version

### CODE REVIEW

File: sparkle/src/components/DataTable.tsx [hunk 1]
```diff
@@ -37,6 +38,7 @@ export function DataTable<TData extends TBaseData, TValue>({
   filter,
   filterColumn,
   initialColumnOrder,
+  mobileHiddenColumns = [],
```
Comment (tdraier) [inline sparkle/src/components/DataTable.tsx:41]: can we have something more flexible like 
`columnsBreakpoints={{ "lastUpdated": "sm" , "otherColumn": "md" }}` ?

Comment (JulesBelveze) [reply sparkle/src/components/DataTable.tsx:41]: Sure, definitely better 👌🏼

**Review by tdraier — APPROVED** [review]
