### PR TITLE
[connectors] - fix: improve logging for errors during data upload

### LINKED ISSUE #5358: Better Logging in `upsertTableFromCsv`
Full trace:
```
Error: Error uploading structured data to Dust.
    at upsertTableFromCsv (/app/src/lib/data_sources.ts:538:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at renderAndUpsertPageFromCache (/app/src/connectors/notion/temporal/activities.ts:1731:9)
    at NotionCastKnownErrorsInterceptor.execute (/app/src/connectors/notion/temporal/cast_known_errors.ts:20:14)
    at ActivityInboundLogInterceptor.execute (/app/src/lib/temporal_monitoring.ts:82:14)
    at Activity.execute (/app/node_modules/@temporalio/worker/src/activity.ts:117:14)
    at <anonymous> (/app/node_modules/@temporalio/worker/src/activity.ts:144:24)
    at <anonymous> (/app/node_modules/@temporalio/worker/src/worker.ts:974:24)
```

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

Better logging in `upsertTableFromCsv` to get better understanding of the following error:
```
Error uploading structured data to Dust
```

### CODE REVIEW

File: connectors/src/lib/data_sources.ts [hunk 1]
```diff
@@ -523,12 +523,12 @@ export async function upsertTableFromCsv({
         config: { ...e.config, data: undefined },
       };
       localLogger.error(
-        { error: sanitizedError },
-        "Error uploading structured data to Dust."
+        { error: sanitizedError, payload: dustRequestPayload },
```
Comment (JulesBelveze) [inline connectors/src/lib/data_sources.ts:526]: Will that be too much logging??

Comment (fontanierh) [reply connectors/src/lib/data_sources.ts:526]: Adding the payload here will dump the whole CSV on datadog. It could be fine while debugging, but let's remove this very quick once you have the log you need.

**Review by fontanierh — APPROVED** [review]

File: connectors/src/lib/data_sources.ts (hunk 1 above)
Comment (JulesBelveze) [reply connectors/src/lib/data_sources.ts:526]: Sure! Adding a note to myself
