### PR TITLE
fix: automatically compute max_tokens for claude

### LINKED ISSUE #1596: Claude has a max_token issue

### PR DESCRIPTION
**Pull request by spolu**
Fixes #1596

### CODE REVIEW

File: core/src/providers/anthropic.rs [hunk 1]
```diff
@@ -106,15 +106,29 @@ impl AnthropicLLM {
...
     ) -> Result<LLMChatGeneration> {
         assert!(self.api_key.is_some());
 
         let prompt = self.chat_prompt(messages);
+
         let mut stop_tokens = stop.clone();
         stop_tokens.push(String::from("\n\nHuman:"));
         stop_tokens.push(String::from("\n\nAssistant:"));
 
+        match max_tokens {
```
Comment (fontanierh) [inline core/src/providers/anthropic.rs:119]: Could this be simplified as `if max_tokens.is_none() || max_tokens.unwrap() == -1) {...}` or a slightly rustier version of that ? 
Could also avoid the `mut` and assign to a new var

**Review by fontanierh — DISMISSED** [review]
small nit / question but LGTM

File: core/src/providers/anthropic.rs (hunk 1 above)
Comment (spolu) [reply core/src/providers/anthropic.rs]: Updated :+1:
