### PR TITLE
[front] - enhance: scrolling behavior

### LINKED ISSUE #5671: Improve scrolling behavior
Auto-scrolling is a bit broken since it keeps moving as tokens get streamed which prevent users from reading the text at the beginning of the message if streaming is fast.

Investigate what other platforms are doing (chatGPT, Claude, Anthropic), then define and implement a better UX.

Our current belief is that the best experience would be:

As the new agent message appear we scroll to it at a distance from top roughly equal to a 2 liner user message
Let the model generate but don't auto-scroll
it's more challenging than it looks to properly implement.

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

This PR aims at improving the scrolling behaviour in the conversation views. It resume works done in this PR: https://github.com/dust-tt/dust/pull/5690

The idea is the following: 
- when a user sends a new message the conversation gets scrolled up and the agent message is added into a div with a minimum height. 
- we use an `IntersectionObserver` to remove the extra height from the div as soon as it leaves the viewport
- if the agent message is too long we do not scroll to the end of the message

## Risk

Break UI

## Deploy Plan

- Deploy to `front-edge`
- Deploy to `front`

### CODE REVIEW

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 1]
```diff
@@ -384,31 +384,43 @@ const ConversationViewer = React.forwardRef<
...
-                    : undefined
-                }
-                user={user}
-                isLastMessage={latestPage?.messages.at(-1)?.sId === message.sId}
-                latestMentions={latestMentions}
-              />
-            );
-          });
-        })}
+      {typedGroupedMessages.map((typedGroup, index) => {
```
Comment (spolu) [inline front/components/assistant/conversation/ConversationViewer.tsx:387]: is it expected to not condition on `conversation` anymore?

File: front/components/assistant/conversation/messages/MessageGroup.tsx [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+const OFFSET_FROM_WINDOW = 450;
+
+export default function MessageGroup({
+  messages,
+  isLastMessage,
+  children,
+}: MessageGroupProps) {
+  const lastMessageRef = useRef<HTMLDivElement>(null);
+
+  const shouldMaximize = React.useMemo(() => {
```
Comment (spolu) [inline front/components/assistant/conversation/messages/MessageGroup.tsx:20]: Naming can be improved :+1:

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 3]
```diff
@@ -360,6 +356,10 @@ const ConversationViewer = React.forwardRef<
   const eventIds = useRef<string[]>([]);
 
   const groupedMessages = useMemo(() => groupMessages(messages), [messages]);
+  const typedGroupedMessages: MessageWithContentFragmentsType[][][] =
+    groupMessagesByType(groupedMessages);
+
+  useLastMessageGroupObserver(typedGroupedMessages);
```
Comment (spolu) [inline front/components/assistant/conversation/ConversationViewer.tsx:362]: Not sure I follow how this is used?

**Review by spolu — COMMENTED** [review]
Looks very nice!

File: front/hooks/useLastMessageGroupObserver.ts [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+  messages: MessageWithContentFragmentsType[][][]
+) {
+  useEffect(() => {
+    const observer = new IntersectionObserver(
+      (entries) => {
+        entries.forEach((entry) => {
+          const target = entry.target as HTMLElement;
+          // Adjust the minHeight based on the intersecting status.
+          if (!entry.isIntersecting) {
+            target.style.minHeight = "0px";
```
Comment (spolu) [inline front/hooks/useLastMessageGroupObserver.ts:18]: Ah I see it now here 👍

File: front/components/assistant/conversation/messages/MessageGroup.tsx [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+    if (isLastMessage && lastMessageRef.current) {
+      lastMessageRef.current.scrollIntoView({ behavior: "smooth" });
+    }
+  }, [isLastMessage]);
+
+  return (
+    <div
+      className={isLastMessage ? "last-message-group" : ""}
+      ref={isLastMessage ? lastMessageRef : undefined}
+      style={{ minHeight: dynamicMinHeight }}
```
Comment (spolu) [inline front/components/assistant/conversation/messages/MessageGroup.tsx:50]: Should we use tailwind?

Comment (spolu) [reply front/components/assistant/conversation/messages/MessageGroup.tsx:50]: I presume the value of style vs tailwind is that you can mutate it from the observer?

Wouldn't it be cleaner to have the observer return a value that we can then use here?

Comment (JulesBelveze) [reply front/components/assistant/conversation/messages/MessageGroup.tsx:50]: I initially tried using Tailwind classes here (something like `min-h-[200px]`) but couldn't have it work

Comment (JulesBelveze) [reply front/components/assistant/conversation/messages/MessageGroup.tsx:50]: Not sure I fully understood but seems like Tailwind can't recognize and apply styles for dynamically generated class names that depend on JavaScript runtime values.

File: front/components/assistant/conversation/ConversationViewer.tsx (hunk 1 above)
Comment (JulesBelveze) [reply front/components/assistant/conversation/ConversationViewer.tsx]: Overlooked this my bad

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 6]
```diff
@@ -360,6 +360,10 @@ const ConversationViewer = React.forwardRef<
   const eventIds = useRef<string[]>([]);
 
   const groupedMessages = useMemo(() => groupMessages(messages), [messages]);
+  const typedGroupedMessages: MessageWithContentFragmentsType[][][] =
+    groupMessagesByType(groupedMessages);
```
Comment (flvndvd) [inline front/components/assistant/conversation/ConversationViewer.tsx:364]: Let's do one function? Always memoize 😉.

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 7]
```diff
@@ -449,3 +466,36 @@ const groupMessages = (
...
+      const lastGroupType = lastGroup?.[0]?.[0]?.type;
+
+      if (!lastGroup || currentMessageType !== lastGroupType) {
+        typedGroupsAcc.push([currentMessage]);
+      } else {
+        lastGroup.push(currentMessage);
+      }
+
+      if (isLastMessage && currentMessageType === "user_message") {
+        typedGroupsAcc.push([]);
```
Comment (flvndvd) [inline front/components/assistant/conversation/ConversationViewer.tsx:495]: Not sure to understand why we do this 🤔 ?

File: front/components/assistant/conversation/messages/MessageGroup.tsx [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+
+import type { MessageWithContentFragmentsType } from "@app/components/assistant/conversation/ConversationViewer";
+
+interface MessageGroupProps {
+  messages: MessageWithContentFragmentsType[][];
+  isLastMessage: boolean;
+  children?: React.ReactNode;
+}
+
+const VIEWPORT_OFFSET = 450; // More generic term
```
Comment (flvndvd) [inline front/components/assistant/conversation/messages/MessageGroup.tsx:11]: ??

Comment (flvndvd) [reply front/components/assistant/conversation/messages/MessageGroup.tsx:11]: Let's maybe add a comment.

File: front/components/assistant/conversation/messages/MessageGroup.tsx [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+}: MessageGroupProps) {
+  const lastMessageRef = useRef<HTMLDivElement>(null);
+
+  const shouldExpandHeight = useMemo(() => {
+    if (!messages || !messages[0] || !messages[0][0]) {
+      return true;
+    }
+    const initialMessage = messages[0][0];
+
+    if (initialMessage.type === "user_message") {
```
Comment (flvndvd) [inline front/components/assistant/conversation/messages/MessageGroup.tsx:26]: Let's use typeguard

File: front/hooks/useLastMessageGroupObserver.ts [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+          }
+        });
+      },
+      { threshold: 0 }
+    );
+
+    const element = document.querySelector(".last-message-group");
```
Comment (flvndvd) [inline front/hooks/useLastMessageGroupObserver.ts:25]: Let's avoid magic variable like this and use a constant 🙏.

**Review by flvndvd — COMMENTED** [review]
Looks great 🔥 !

Tested only empty user messages, and the experience feels weird, we should probably not create a white div if there is no mentions?

Lost padding as well:

image

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 11]
```diff
@@ -359,7 +360,15 @@ const ConversationViewer = React.forwardRef<
   });
   const eventIds = useRef<string[]>([]);
 
-  const groupedMessages = useMemo(() => groupMessages(messages), [messages]);
+  // const groupedMessages = useMemo(() => groupMessages(messages), [messages]);
```
Comment (flvndvd) [inline front/components/assistant/conversation/ConversationViewer.tsx]: ✂️

File: front/components/assistant/conversation/ConversationViewer.tsx (hunk 7 above)
Comment (JulesBelveze) [reply front/components/assistant/conversation/ConversationViewer.tsx]: Changed the logic, we don't need it anymore

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 12]
```diff
@@ -384,68 +393,102 @@ const ConversationViewer = React.forwardRef<
...
-              />
-            );
-          });
+        typedGroupedMessages.map((typedGroup, index) => {
+          const isLastGroup = index === typedGroupedMessages.length - 1;
+          return (
+            <MessageGroup
+              key={`typed-group-${index}`}
+              messages={typedGroup}
+              isLastMessage={isLastGroup}
```
Comment (flvndvd) [inline front/components/assistant/conversation/ConversationViewer.tsx:400]: `nit`
```suggestion
              isLastGroup={isLastGroup}
```

**Comment by JulesBelveze** [comment]
> Tested only empty user messages, and the experience feels weird, we should probably not create a white div if there is no mentions?
Lost padding as well:

Was able to reproduce it and should be fixed now 👍🏼

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 13]
```diff
@@ -384,68 +393,102 @@ const ConversationViewer = React.forwardRef<
...
+            >
+              {typedGroup &&
```
Comment (flvndvd) [inline front/components/assistant/conversation/ConversationViewer.tsx:402]: Why this logic is here? It should probably be in `MessageGroup`, right?

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 14]
```diff
@@ -384,68 +393,102 @@ const ConversationViewer = React.forwardRef<
...
+                    return (
+                      <MessageItem
+                        key={`message-${message.sId}`}
+                        conversationId={conversationId}
+                        hideReactions={hideReactions}
+                        isInModal={isInModal}
+                        message={message}
+                        owner={owner}
+                        reactions={reactions}
+                        ref={
```
Comment (flvndvd) [inline front/components/assistant/conversation/ConversationViewer.tsx:414]: This logic was used for pagination but I guess it should not be moved to the MessageGroup level.

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 15]
```diff
@@ -384,68 +393,102 @@ const ConversationViewer = React.forwardRef<
...
+ * and attaching them to subsequent user_messages, then groups these messages
+ * by type, ensuring consecutive messages of the same type are grouped together.
+ *
+ */
+const groupMessagesByType = (
   messages: FetchConversationMessagesResponse[]
-): MessageWithContentFragmentsType[][] => {
-  const groups: MessageWithContentFragmentsType[][] = [];
+): MessageWithContentFragmentsType[][][] => {
+  const typedGroupsAcc: MessageWithContentFragmentsType[][][] = [];
```
Comment (flvndvd) [inline front/components/assistant/conversation/ConversationViewer.tsx:449]: `nit` Accumulator sounds like we do a reduce 🙃

File: front/components/assistant/conversation/messages/MessageGroup.tsx [hunk 16]
```diff
@@ -0,0 +1,63 @@
...
+interface MessageGroupProps {
+  messages: MessageWithContentFragmentsType[][];
+  isLastMessage: boolean;
+  children?: React.ReactNode;
+}
+
+// arbitrary offset to scroll the last MessageGroup to
+const VIEWPORT_OFFSET = 450;
+
+export const LAST_MESSAGE_GROUP_CLASS = "last-message-group";
```
Comment (flvndvd) [inline front/components/assistant/conversation/messages/MessageGroup.tsx:15]: We should probably use id here instead of class.

File: front/components/assistant/conversation/messages/MessageGroup.tsx [hunk 17]
```diff
@@ -0,0 +1,63 @@
...
+  const shouldExpandHeight = useMemo(() => {
+    if (messages.length === 0) {
+      return false;
+    }
+    const initialMessageGroup = messages[0];
+    if (initialMessageGroup.length === 0) {
+      return false;
+    }
+
+    const initialMessage = messages[0][0];
```
Comment (flvndvd) [inline front/components/assistant/conversation/messages/MessageGroup.tsx:33]:
```suggestion
    const initialMessage = initialMessageGroup[0];
```

OR

```suggestion
    const [initialMessage] = initialMessageGroup;
```

File: front/components/assistant/conversation/ConversationViewer.tsx [hunk 18]
```diff
@@ -384,68 +389,85 @@ const ConversationViewer = React.forwardRef<
...
 export default ConversationViewer;
 
-// Grouping messages into arrays based on their type, associating content_fragments with the upcoming following user_message.
-// Example:
-// Input [[content_fragment, content_fragment], [user_message], [agent_message, agent_message]]
-// Output: [[user_message with content_fragment[]], [agent_message, agent_message]]
-// This structure enables layout customization for consecutive messages of the same type
-// and displays content_fragments within user_messages.
-const groupMessages = (
+/**
```
Comment (flvndvd) [inline front/components/assistant/conversation/ConversationViewer.tsx:419]: Please keep the comment or update it, at least we need the example.

File: front/components/assistant/conversation/messages/MessageGroup.tsx [hunk 19]
```diff
@@ -0,0 +1,110 @@
...
+  isInModal,
+  owner,
+  reactions,
+  prevFirstMessageId,
+  prevFirstMessageRef,
+  user,
+  latestPage,
+  latestMentions,
+}: MessageGroupProps) {
+  const lastMessageRef = useRef<HTMLDivElement>(null);
```
Comment (flvndvd) [inline front/components/assistant/conversation/messages/MessageGroup.tsx:47]:
```suggestion
  const lastMessageGroup = useRef<HTMLDivElement>(null);
```

File: front/components/assistant/conversation/messages/MessageGroup.tsx [hunk 20]
```diff
@@ -0,0 +1,110 @@
...
+              hideReactions={hideReactions}
+              isInModal={isInModal}
+              message={message}
+              owner={owner}
+              reactions={reactions}
+              ref={
+                message.sId === prevFirstMessageId
+                  ? prevFirstMessageRef
+                  : undefined
+              }
```
Comment (flvndvd) [inline front/components/assistant/conversation/messages/MessageGroup.tsx:100]: Ideally we don't need this as we scope down to `MessageGroup` ... but it's tricky since messageGroup already has a ref.

File: front/components/assistant/conversation/messages/MessageItem.tsx [hunk 21]
```diff
@@ -48,7 +48,7 @@ const MessageItem = React.forwardRef<HTMLDivElement, MessageItemProps>(
     switch (type) {
       case "user_message":
         return (
-          <div key={`message-id-${sId}`} ref={ref}>
+          <div className="mt-2" key={`message-id-${sId}`} ref={ref}>
```
Comment (flvndvd) [inline front/components/assistant/conversation/messages/MessageItem.tsx:51]: This should live in `ConversationMessage`.

**Comment by flvndvd** [comment]
I hit an issue on the pagination, reloading a conversation with more than one page, leads to a surge of requests:
image

**Comment by JulesBelveze** [comment]
> I hit an issue on the pagination, reloading a conversation with more than one page, leads to a surge of requests:

As per IRL we found out that this behaviour was not introduced by this PR.

@flvndvd if there's no other issue, should we merge this PR and tackle this pagination issue separately ? (To avoid this PR staling)

**Review by flvndvd — APPROVED** [review]
LGTM 🔥 🔥 🔥 🔥

**Comment by spolu** [comment]
wooot!
