### PR TITLE
Fix support for `dust-application/slack` content fragment

### LINKED ISSUE #8986: Bug: slack attachments are not presented in list files
Example conversation: https://dust.tt/w/0ec9852c2f/assistant/21WstzG1Uh
First run: https://dust.tt/w/78bda07b39/spaces/vlt_rICtlrSEpWqX/apps/0e9889c787/runs/2c27e0691b14e151dc51ec36c2d4fc896769d1119eff266c8fc3616fe842cb93

Original slack thread: https://dust4ai.slack.com/archives/C050SM8NSPK/p1732725667352009
Context: https://dust4ai.slack.com/archives/C050SM8NSPK/p1732789521915019

### PR DESCRIPTION
**Pull request by spolu**
## Description

Fixes https://github.com/dust-tt/dust/issues/8986

Comment explains the PR. Not tested will optimistically test in production.

## Risk

N/A. Behind flag.

## Deploy Plan

- deploy `front`

### CODE REVIEW

**Review by Fraggle — APPROVED** [review]

File: front/lib/api/assistant/jit_actions.ts [hunk 1]
```diff
@@ -130,7 +140,7 @@ export function listFiles(
 
     if (
       isContentFragmentType(m) &&
-      isSupportedPlainTextContentType(m.contentType) &&
+      !isListableContentType(m.contentType) &&
```
Comment (Fraggle) [inline front/lib/api/assistant/jit_actions.ts:143]: ! ?
