### PR TITLE
[connectors] - fix(microsoft): data sour selection tree

### LINKED ISSUE #6199: [MS Connector] Fix display of selected items in add/remove view (and selection of items in assistant builder)
Currently, they do not show properly
Related PR: #6086 initiated by @tdraier 
Code has changed a bit since then => maybe restart one taking inspiration from it

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

This PR aims at fixing the broken behaviour of the data source selection tree for the Microsoft connector.

**References**:
- #6199 

## Risk

n\a

## Deploy Plan

n\a

### CODE REVIEW

**Comment by JulesBelveze** [comment]
@philipperolet Just a heads up: we do display folders without any synced file inside (see folders "xxx" and "folder_with_md" in the screenshot).

Screenshot 2024-07-18 at 21 25 38

Fixing this behaviour requires to have the full tree computed when displaying nodes. This doesn't introduce any misbehaviour just a non optimal UX. Are we okay to have it like this for now  to ship Microsoft at the end of the week ?  I can tackle this  issue later this summer.

File: connectors/src/connectors/microsoft/index.ts [hunk 1]
```diff
@@ -32,6 +34,7 @@ import {
   launchMicrosoftFullSyncWorkflow,
   launchMicrosoftIncrementalSyncWorkflow,
 } from "@connectors/connectors/microsoft/temporal/client";
+import { MicrosoftNodeModel } from "@connectors/lib/models/microsoft";
```
Comment (philipperolet) [inline connectors/src/connectors/microsoft/index.ts:37]: hmm we shouldn't have sequelize/models imported in here
the logic should move to resource or elsewhere; will have a look below to see where

File: connectors/src/connectors/microsoft/index.ts [hunk 2]
```diff
@@ -227,11 +238,10 @@ export class MicrosoftConnectorManager extends BaseConnectorManager<null> {
       }
       case "drive":
       case "folder": {
-        const folders = (
-          await getAllPaginatedEntities((nextLink) =>
-            getFilesAndFolders(client, parentInternalId, nextLink)
-          )
-        ).filter((n) => n.folder);
+        const filesAndFolders = await getAllPaginatedEntities((nextLink) =>
```
Comment (philipperolet) [inline connectors/src/connectors/microsoft/index.ts:241]: not absolutely necessary IMHO but fine :)

File: connectors/src/connectors/microsoft/index.ts [hunk 3]
```diff
@@ -495,3 +509,26 @@ export async function getClient(connectionId: NangoConnectionId) {
     authProvider: (done) => done(null, msAccessToken),
   });
 }
+
+export async function retrieveChildrenNodes(
```
Comment (philipperolet) [inline connectors/src/connectors/microsoft/index.ts:513]: yeah I think that should be in the MicrosoftNodeResource
I think there's a fetchChildren already there btw

File: connectors/src/connectors/microsoft/lib/content_nodes.ts [hunk 4]
```diff
@@ -161,3 +162,59 @@ export function getFolderAsContentNode(
...
   };
 }
+
+export function getFileAsContentNode(
+  file: microsoftgraph.DriveItem,
+  parentInternalId: string
+): ContentNode {
+  return {
+    provider: "microsoft",
+    internalId: internalIdFromTypeAndPath({
```
Comment (philipperolet) [inline connectors/src/connectors/microsoft/lib/content_nodes.ts:172]: this is refactored on the incremental sync PR by ag getDriveItemInternalId function
I will merge the incr sync pr even if it requires some more testing to avoid diverging with our various refactorings

File: connectors/src/connectors/microsoft/lib/content_nodes.ts [hunk 5]
```diff
@@ -161,3 +162,59 @@ export function getFolderAsContentNode(
...
+    sourceUrl: "",
+    dustDocumentId: null,
+    lastUpdatedAt: null,
+    expandable: false,
+    permission: "none",
+  };
+}
+
+export function getMicrosoftNodeAsContentNode(
+  node: MicrosoftNodeModel,
```
Comment (philipperolet) [inline connectors/src/connectors/microsoft/lib/content_nodes.ts:188]: no model here; resources or the  MicrosoftNodeType

**Review by philipperolet — COMMENTED** [review]
Thanks :+1: left a few coms, will merge the incremental sync PR first

**Review by philipperolet — APPROVED** [review]
LGTM pending rebase :)
