### PR TITLE
[Microsoft] Fix: insert folder for spreadsheet

### LINKED ISSUE #10150: Fix: tables in microsoft not inserted in nodes as folders
Derived from https://github.com/dust-tt/dust/issues/10009

In microsoft, spreadsheets contain multiple sheets. But they are not sheets themselves. As such, they are not stored in tables. Nor anywhere else. However, they are used as parents.
We should store them, as folders.

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Closes #10150
Similar to #10009

To browse individual sheets, we must store the existence of the parent spreadsheet. It is stored as a folder (includes backfill)

Risk
---
low, risk having unwarranted folders which we can see easily / change easily

Deploy
---
connectors
run backfill

### CODE REVIEW

File: types/src/shared/internal_mime_types.ts [hunk 1]
```diff
@@ -88,7 +88,7 @@ export const MIME_TYPES = {
   }),
   MICROSOFT: getMimeTypes({
     provider: "microsoft",
-    resourceTypes: ["FOLDER"], // for files and spreadsheets, we keep Microsoft's mime types
+    resourceTypes: ["FOLDER", "SPREADSHEET"], // for files and spreadsheets, we keep Microsoft's mime types
```
Comment (aubin-tchoi) [inline types/src/shared/internal_mime_types.ts:91]: nit: the comment is outdated

**Review by aubin-tchoi — APPROVED** [review]
LGTM 👍
