### PR TITLE
Github: process issue/discussion pages in their own workflows

### LINKED ISSUE #3992: Failed Github initial sync workflow due to history size
Full context here: https://dust4ai.slack.com/archives/C05F84CFP0E/p1709059274907799

### PR DESCRIPTION
**Pull request by spolu**
## Description

Fixes: https://github.com/dust-tt/dust/issues/3992

Move issues/discussions page processing in their own workflow to prevent `Workflow history size / count exceeds limit.`
Also bumps concurrency of processing issues/discussions to 8

Command to restart the full-sync:

```
./admin/cli.ts connectors full-resync --wId 2ddbc0204d --dataSourceName managed-github
```

Original cancelled workflow: https://cloud.temporal.io/namespaces/dust-prod.gmnlm/workflows/workflow-github-full-sync-2ddbc0204d-managed-github-repo-452716694-syncCodeOnly-false/b62c531e-c0c7-4dee-82a6-5cfca3b346e6/history

## Risk

N/A

## Deploy Plan

- deploy connectors and prodbox
- restart full sync workflow from issue related

### CODE REVIEW

File: connectors/src/connectors/github/temporal/workflows.ts [hunk 1]
```diff
@@ -98,11 +98,13 @@ export async function githubFullSyncWorkflow(
             },
             args: [
               dataSourceConfig,
+              connectorId.toString(),
```
Comment (fontanierh) [inline connectors/src/connectors/github/temporal/workflows.ts:101]: since we're changing the args can we make them an object 😇  ?

**Review by fontanierh — APPROVED** [review]
looking good
