### PR TITLE
fix: prevent potential email abuse on invitations endpoint

### LINKED ISSUE #4555: Potential Email Abuse in Dust Workspace
## Description:

When a user is in a workspace, they can invite other users by entering their email addresses on the members page). A POST request is then sent to the API (`/invitations`) with the email address in the data, and an invitation email is sent to the specified address.

An attacker can abuse this functionality to send multiple emails to a targeted person or to spam multiple users. This could potentially harm the reputation of the "dust.tt" domain, causing it to be blacklisted as a spam domain.

## Impact:

Abuse of the email invitation system can lead to spamming and harm the reputation of the Dust workspace and the associated domain.

## Recommendations:

To mitigate this vulnerability, we should implement the following measures:
- Verify that a user cannot send the same invitation to the same user multiple times, or limit the number of sends to 5.
- Limit the number of invitations sent by a user within a short time frame (e.g., 10 invitations per minute).

### PR DESCRIPTION
**Pull request by fontanierh**
## Description

fixes https://github.com/dust-tt/dust/issues/4555

Limits the # of email invitations a workspace can send every day (50). 
Prevents sending several invitations to the same email for the same workspace within a day

### CODE REVIEW

File: front/pages/api/w/[wId]/invitations/index.ts [hunk 1]
```diff
@@ -152,7 +158,48 @@ async function handler(
         });
       }
       const existingMembers = await getMembers(auth);
-
+      const unconsumedInvitations = await MembershipInvitation.findAll({
```
Comment (flvndvd) [inline front/pages/api/w/[wId]/invitations/index.ts:161]: Let's move this to the `lib/api/*` (see [thread](https://dust4ai.slack.com/archives/C050SM8NSPK/p1712230956371889))

File: front/pages/api/w/[wId]/invitations/index.ts [hunk 2]
```diff
@@ -152,7 +158,48 @@ async function handler(
...
+        where: {
+          workspaceId: owner.id,
+          status: ["pending", "revoked"],
```
Comment (flvndvd) [inline front/pages/api/w/[wId]/invitations/index.ts:164]: Should we account for `revoked` in there?

File: front/pages/api/w/[wId]/invitations/index.ts [hunk 3]
```diff
@@ -152,7 +158,48 @@ async function handler(
...
+          createdAt: {
+            [Op.gte]: new Date(new Date().setHours(0, 0, 0, 0)),
```
Comment (flvndvd) [inline front/pages/api/w/[wId]/invitations/index.ts:166]: `nit`
const startOfDay = new Date();
startOfDay.setUTCHours(0, 0, 0, 0);

File: front/pages/api/w/[wId]/invitations/index.ts [hunk 4]
```diff
@@ -152,7 +158,48 @@ async function handler(
...
+      const emailsWithRecentUnconsumedInvitations = new Set(
+        unconsumedInvitations
+          .filter(
+            (i) =>
+              i.createdAt.getTime() >
+              new Date().getTime() - UNCONSUMED_INVITATION_COOLDOWN_PER_EMAIL_MS
+          )
+          .map((i) => i.inviteEmail.toLowerCase().trim())
+      );
+      if (
```
Comment (flvndvd) [inline front/pages/api/w/[wId]/invitations/index.ts:188]: Assuming one email address already has a fresh recent invitation, the entire operation will fail?

Comment (fontanierh) [reply front/pages/api/w/[wId]/invitations/index.ts:188]: yes, would you prefer that we only filter those out ?

File: front/pages/api/w/[wId]/invitations/index.ts (hunk 3 above)
Comment (fontanierh) [reply front/pages/api/w/[wId]/invitations/index.ts:166]: sure

File: front/pages/api/w/[wId]/invitations/index.ts (hunk 2 above)
Comment (fontanierh) [reply front/pages/api/w/[wId]/invitations/index.ts:166]: Yeah because otherwise you can just revoke and re-send. Maybe we should discard revoked ones that are too old ? TBH if you have more than a few revoked it's fishy

Comment (flvndvd) [reply front/pages/api/w/[wId]/invitations/index.ts:166]: But what happens when you have revoked 50 invitations, you can't invite anymore?

File: front/pages/api/w/[wId]/invitations/index.ts (hunk 4 above)
Comment (flvndvd) [reply front/pages/api/w/[wId]/invitations/index.ts:190]: I mean as long as we have an explicit error message in the UI and the user does not lose its email addresses list, I'm fine.

File: front/pages/api/w/[wId]/invitations/index.ts (hunk 2 above)
Comment (fontanierh) [reply front/pages/api/w/[wId]/invitations/index.ts]: Simplified the whole thing. Now were just looking at invitations from the last 24 hours. IMO it's enough to limit abuse.

**Review by flvndvd — APPROVED** [review]
LGTM

File: front/pages/api/w/[wId]/invitations/index.ts [hunk 5]
```diff
@@ -152,7 +154,39 @@ async function handler(
...
+        return apiError(req, res, {
+          status_code: 400,
+          api_error: {
+            type: "invalid_request_error",
+            message: `Too many unconsumed invitations. Please ask your members to consume their invitations before sending more.`,
+          },
+        });
+      }
+      const emailsWithRecentUnconsumedInvitations = new Set(
+        unconsumedInvitations.map((i) => i.inviteEmail.toLowerCase().trim())
```
[the remark this answers is not in the document]
Comment (fontanierh) [reply front/pages/api/w/[wId]/invitations/index.ts:173]: ceinture bretelles

**Review by flvndvd — APPROVED** [review]
